version: '3.2'
 
services:
 elasticsearch:
   image: docker.elastic.co/elasticsearch/elasticsearch:7.17.3
   volumes:
     - elasticsearch_db:/usr/share/elasticsearch/data
     - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
   ports:
     - 9200:9200
     - 9300:9300
   environment:
     ES_JAVA_OPTS: "-Xmx1g -Xms1g"
     ELASTIC_PASSWORD: elastic
     KIBANA_PASWORD: elastic

 kibana:
   image: docker.elastic.co/kibana/kibana:7.17.3
   volumes:
     - ./kibana.yml:/usr/share/kibana/config/kibana.yml
   ports:
     - 5601:5601
   depends_on:
     - elasticsearch

volumes:
  elasticsearch_db:
