---
- hosts: proxy
  user: root
  become: true
  roles:
    - create_user
    - configure_server
    - install_metrics
    - node_exporter
    - dc_nginxproxy
 
- hosts: cloud
  become_user: atlas
  roles:
    - install_metrics
    - node_exporter          
    - dc_nextcloud-mysql
    
 
