---
- name: install iptables
  ansible.builtin.dnf:
    name: iptables
    state: present

- name: add repo EPEL and ELREPO
  ansible.builtin.dnf:
    name:
      - epel-release
      - elrepo-release
    state: present    

- name: install wireguard and kmode
  ansible.builtin.dnf:
    name:
      - wireguard-tools
      - kmod-wireguard
    state: present

- name: set forwarding IPv4
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes

- name: create wg-server keys
  ansible.builtin.shell:
    cmd: umask 077 && wg genkey | tee privatekey | wg pubkey > pubkey
    chdir: /etc/wireguard
    
- name: create wg-peer1 keys
  ansible.builtin.shell:
    cmd: umask 077 && wg genkey | tee cloudpriv | wg pubkey > cloudpub
    chdir: /etc/wireguard
  

- name: create wg-peer2 keys
  ansible.builtin.shell:
    cmd: umask 077 && wg genkey | tee monitorpriv | wg pubkey > monitorpub
    chdir: /etc/wireguard

- name: temlete wg0.conf
  ansible.builtin.template:
    src: wg0.j2
    dest: /etc/wireguard/wg0.conf
    owner: root
    group: root
    mode: 0600 

- name: add keys
  shell: 
    cmd: sed -i "s/PrivateKey =/PrivateKey = $(cat privatekey)/" wg0.conf  
    chdir: /etc/wireguard/

- name: add keys
  shell: 
    cmd: sed -i "10 s/PublicKey =/PublicKey = $(cat cloudpub)/" wg0.conf  
    chdir: /etc/wireguard/

- name: add keys
  shell:
    cmd: sed -i "14 s/PublicKey = /PublicKey = $(cat monitorpub)/" wg0.conf
    chdir: /etc/wireguard/    
