---
- name: install iptables
  ansible.builtin.dnf:
    name: iptables
    state: present

- name: add repo EPEL and ELREPO
  ansible.builtin.dnf:
    name:
      - epel-release
      - elrepo-release
    state: present    

- name: install wireguard and kmode
  ansible.builtin.dnf:
    name:
      - wireguard-tools
      - kmod-wireguard
    state: present

- name: set forwarding IPv4
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes

- name: create wg-server keys
  ansible.builtin.shell:
    cmd: umask 077 && wg genkey | tee privatekey | wg pubkey > pubkey
    chdir: /etc/wireguard
    
- name: create wg-peer1 keys
  ansible.builtin.shell:
    cmd: umask 077 && wg genkey | tee cloudpriv | wg pubkey > cloudpub
    chdir: /etc/wireguard
  

- name: create wg-peer2 keys
  ansible.builtin.shell:
    cmd: umask 077 && wg genkey | tee monitorpriv | wg pubkey > monitorpub
    chdir: /etc/wireguard

- name: copy wg0.conf
  ansible.builtin.copy:
    src: wg0.conf
    dest: /etc/wireguard/
    owner: root
    group: root
    mode: 0600  

- name: add keys
  shell: 
    cmd: sed -i "s/PrivateKey =/PrivateKey = $(cat privatekey)/" wg0.conf  
    chdir: /etc/wireguard/

- name: add keys
  shell: 
    cmd: sed -i "10 s/PublicKey =/PublicKey = $(cat cloudpub)/" wg0.conf  
    chdir: /etc/wireguard/

- name: add keys
  shell:
    cmd: sed -i "14 s/PublicKey =/PublicKey = $(cat monitorpub)/" wg0.conf
    chdir: /etc/wireguard/

- name: show pubkey
  shell: cat /etc/wireguard/pubkey
  register: pubkey

- name: show cloud privkey
  shell: cat /etc/wireguard/cloudpriv
  register: cloudpriv

- name: show monitorpiv
  shell: cat /etc/wireguard/monitorpriv
  register: monitorpriv

- debug: 
    var: pubkey.stdout
      
- debug:
    var: cloudpriv.stdout

- debug:    
    var: monotorpriv.stdout
