---
- name: curl download from url
  ansible.builtin.get_url:
    url: https://github.com/docker/compose/releases/download/v2.7.0/docker-compose-linux-x86_64 
    dest: /usr/bin/docker-compose
    owner: root
    group: root
    mode: 0755

- name: get ohmyzsh
  ansible.builtin.get_url:
    url: https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: /home/atlas/omzsh.sh

               
      


